vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       events:
           uri_prefix: '%events%'
           upload_destination: '%kernel.project_dir%/public%events%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: true
           delete_on_update: false
           delete_on_remove: false
